stages:
  - Cluster Setup
  - Kubera-setup
  - Cypress-setup
  - E2E-metrics
  - Cluster Cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &global_cache
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - Cypress/node_modules

EKS Setup:
  stage: Cluster Setup
  tags:
    - kubera-litmus
  script:
    - chmod 755 build/eks/1-cluster-setup/setup
    - ./build/eks/1-cluster-setup/setup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

Kubera Setup:
  when: always
  stage: Kubera-setup
  tags: 
    - kubera-litmus
  script:
    - chmod 755 ./k8s_scripts/install.sh
    - ./k8s_scripts/install.sh
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

Cypress Setup:
  when: always
  stage: Cypress-setup
  tags: 
    - kubera-litmus
  script:
    - cd Cypress && npm ci --prefer-offline

E2E Metric:
  when: always
  stage: E2E-metrics
  tags: 
    - kubera-litmus
  script:
    - chmod 755 ./metrics/e2e-metrics.sh
    - ./metrics/e2e-metrics.sh
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

EKS Cleanup:
    when: always
    stage: Cluster Cleanup
    tags:
      - kubera-litmus
    script:
      - chmod 755 build/eks/2-cluster-cleanup/cleanup
      - ./build/eks/2-cluster-cleanup/cleanup
    artifacts:
      when: always
      paths:
        - .kube/
    cache: {}
