stages:
  - Cluster Setup
  - Kubera-setup
  - Cypress-setup
  - GUI-Tests
  - E2E-metrics
  - Cluster Cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &global_cache
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - Cypress/node_modules

EKS Setup:
  stage: Cluster Setup
  tags:
    - kubera-litmus
  script:
    - chmod 755 build/eks/1-cluster-setup/setup
    - ./build/eks/1-cluster-setup/setup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

Kubera-Setup:
  when: always
  stage: Kubera-setup
  tags: 
    - kubera-litmus
  script:
    - make kubera-install
  artifacts:
    when: always
    paths:
      - .kube/
    reports:
      dotenv: Kubera-Setup.env
  cache: {}

Cypress-Setup:
  when: always
  image: cypress/base:10
  stage: Cypress-setup
  tags: 
    - kubera-litmus
  script:
    - make cypress-install
  needs:
    - job: Kubera-Setup
      artifacts: true

TCID-EC2-Kubera-GUI-Basic:
  when: always
  image: cypress/base:10
  stage: GUI-Tests
  tags: 
    - kubera-litmus
  script:
    - echo "$URL" 
    - cd Cypress && CYPRESS_BASE_URL=$URL npm run BasicTests
  needs:
    - job: Kubera-Setup
      artifacts: true
  cache: {} 

E2E-Metric:
  when: always
  stage: E2E-metrics
  tags: 
    - kubera-litmus
  script:
    - make e2e-metrics
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

EKS Cleanup:
    when: always
    stage: Cluster Cleanup
    tags:
      - kubera-litmus
    script:
      - chmod 755 build/eks/2-cluster-cleanup/cleanup
      - ./build/eks/2-cluster-cleanup/cleanup
    artifacts:
      when: always
      paths:
        - .kube/
    cache: {}
