apiVersion: e2e.mayadata.io/v1alpha1
kind: MasterPlan
metadata:
  name: kubera-litmus-e2e-master-testplan
spec:
  tests:
  # ----------------------------------------------------------
  # Cypress UI Tests for Kubera-Core for Self Cluster
  # ----------------------------------------------------------
  - tcid: TCID-EC2-Kubera-GUI-Auth
    name: "TCID-EC2-Kubera-GUI-Auth"
    description: "UI Tests for Kubera-Core Auth"
    labels:
      test/feature: "Kubera-Core"
      test/tags: "Auth,UI"
      git/location: "https://github.com/mayadata-io/kubera-e2e-litmus/tree/master/test-cases/TCID-EC2-Kubera-GUI-Auth.md"
      test/status: "Done"

  - tcid: TCID-EC2-Kubera-GUI-Github-Auth
    name: "TCID-EC2-Kubera-GUI-Auth"
    description: "UI Tests for Kubera-Core Github-Auth"
    labels:
      test/feature: "Kubera-Core"
      test/tags: "Github-Auth,UI"
      git/location: ""
      test/status: "Not Done"

  - tcid: TCID-EC2-Kubera-GUI-Products-Configuration
    name: "TCID-EC2-Kubera-GUI-Products-Configuration"
    description: "UI Tests for Kubera-Core Products-Configuration"
    labels:
      test/feature: "Kubera-Core"
      test/tags: "Products-Configuration,UI"
      git/location: ""
      test/status: "Not Done"